services:
  app:
    build: ./
    # env_file: devcontainer.env
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    group_add:
      - dialout
    volumes:
      - ..:/workspace:cached
      - /workspace/bin
      - /dev:/dev
      - arduino_data:/home/vscode/.arduino15
    command: sleep infinity
volumes:
  arduino_data:
